development:
  database: shopify_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  database: shopify_test
  pool: 5
  host: localhost

production:
  database: shopify_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres
